"use client"

import * as React from "react"
import { ChevronLeft, ChevronRight } from "lucide-react"
import { DayPicker } from "react-day-picker"
import * as stylex from "@stylexjs/stylex"
import { colors } from "@/styles/tokens.stylex"

// Real class names for react-day-picker (Tailwind is gone), generated by
// StyleX so the utility CSS actually ships.
const dp = stylex.create({
  months: { display: "flex", flexDirection: "column" },
  month: { display: "flex", flexDirection: "column", rowGap: "1rem" },
  caption: {
    display: "flex",
    justifyContent: "center",
    position: "relative",
    alignItems: "center",
    paddingTop: "0.25rem",
  },
  caption_label: { fontSize: "0.875rem", fontWeight: 500 },
  nav: { display: "flex", alignItems: "center", columnGap: "0.25rem" },
  nav_button: {
    height: "1.75rem",
    width: "1.75rem",
    backgroundColor: "transparent",
    padding: 0,
    opacity: 0.5,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "0.375rem",
    borderWidth: 0,
    cursor: "pointer",
    ":hover": { opacity: 1 },
  },
  nav_button_previous: { position: "absolute", left: "0.25rem" },
  nav_button_next: { position: "absolute", right: "0.25rem" },
  table: { width: "100%", borderCollapse: "collapse" },
  head_row: { display: "flex" },
  head_cell: {
    color: colors.gray500,
    width: "2.25rem",
    fontWeight: 400,
    fontSize: "0.8rem",
    textAlign: "center",
  },
  row: { display: "flex", width: "100%", marginTop: "0.5rem" },
  cell: {
    height: "2.25rem",
    width: "2.25rem",
    textAlign: "center",
    fontSize: "0.875rem",
    padding: 0,
    position: "relative",
  },
  day: {
    height: "2.25rem",
    width: "2.25rem",
    padding: 0,
    fontWeight: 400,
    borderRadius: "0.375rem",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.875rem",
    backgroundColor: "transparent",
    borderWidth: 0,
    cursor: "pointer",
    color: colors.foreground,
  },
  day_selected: {
    backgroundColor: colors.blue600,
    color: colors.white,
    fontWeight: 500,
  },
  day_today: { backgroundColor: colors.gray100, fontWeight: 600 },
  day_outside: { color: colors.gray400, opacity: 0.5 },
  day_disabled: { color: colors.gray400, opacity: 0.5 },
  day_hidden: { visibility: "hidden" },
})

function dpClass(key: keyof typeof dp): string {
  const props = stylex.props(dp[key])
  return props.className ?? ""
}

export const calendarStyles = stylex.create({
  root: {
    padding: "0.75rem",
  },
})

// Distribute Omit so the DayPicker prop union (default/single/multiple/range)
// survives; otherwise `mode="single"` + `onSelect` lose their discrimination.
type DistributiveOmit<T, K extends PropertyKey> = T extends unknown
  ? Omit<T, K>
  : never

export type CalendarProps = DistributiveOmit<
  React.ComponentProps<typeof DayPicker>,
  'style' | 'className'
> & {
  style?: stylex.StyleXStyles
}

function Calendar({
  style,
  showOutsideDays = true,
  ...props
}: CalendarProps) {
  return (
    <DayPicker
      showOutsideDays={showOutsideDays}
      {...stylex.props(calendarStyles.root, style)}
      classNames={{
        months: dpClass("months"),
        month: dpClass("month"),
        caption: dpClass("caption"),
        caption_label: dpClass("caption_label"),
        nav: dpClass("nav"),
        nav_button: dpClass("nav_button"),
        nav_button_previous: dpClass("nav_button_previous"),
        nav_button_next: dpClass("nav_button_next"),
        table: dpClass("table"),
        head_row: dpClass("head_row"),
        head_cell: dpClass("head_cell"),
        row: dpClass("row"),
        cell: dpClass("cell"),
        day: dpClass("day"),
        day_selected: dpClass("day_selected"),
        day_today: dpClass("day_today"),
        day_outside: dpClass("day_outside"),
        day_disabled: dpClass("day_disabled"),
        day_hidden: dpClass("day_hidden"),
      }}
      components={{
        IconLeft: () => <ChevronLeft style={{ width: 16, height: 16 }} />,
        IconRight: () => <ChevronRight style={{ width: 16, height: 16 }} />,
      }}
      {...props}
    />
  )
}
Calendar.displayName = "Calendar"

export { Calendar }
