/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as RespondentRouteImport } from './routes/respondent'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as NeutralRouteImport } from './routes/neutral'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClaimantRouteImport } from './routes/claimant'
import { Route as CaseManagerRouteImport } from './routes/case-manager'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as CasesNewRouteImport } from './routes/cases/new'
import { Route as CasesIdRouteImport } from './routes/cases/$id'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminCasesRouteImport } from './routes/admin/cases'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const RespondentRoute = RespondentRouteImport.update({
  id: '/respondent',
  path: '/respondent',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const NeutralRoute = NeutralRouteImport.update({
  id: '/neutral',
  path: '/neutral',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimantRoute = ClaimantRouteImport.update({
  id: '/claimant',
  path: '/claimant',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseManagerRoute = CaseManagerRouteImport.update({
  id: '/case-manager',
  path: '/case-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesNewRoute = CasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/case-manager': typeof CaseManagerRoute
  '/claimant': typeof ClaimantRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/neutral': typeof NeutralRoute
  '/registrar': typeof RegistrarRoute
  '/respondent': typeof RespondentRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/new': typeof CasesNewRoute
  '/cases/': typeof CasesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/case-manager': typeof CaseManagerRoute
  '/claimant': typeof ClaimantRoute
  '/neutral': typeof NeutralRoute
  '/registrar': typeof RegistrarRoute
  '/respondent': typeof RespondentRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/new': typeof CasesNewRoute
  '/cases': typeof CasesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/case-manager': typeof CaseManagerRoute
  '/claimant': typeof ClaimantRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/neutral': typeof NeutralRoute
  '/registrar': typeof RegistrarRoute
  '/respondent': typeof RespondentRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/new': typeof CasesNewRoute
  '/cases/': typeof CasesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/case-manager'
    | '/claimant'
    | '/dashboard'
    | '/neutral'
    | '/registrar'
    | '/respondent'
    | '/unauthorized'
    | '/admin/cases'
    | '/admin/users'
    | '/auth/signin'
    | '/auth/signup'
    | '/cases/$id'
    | '/cases/new'
    | '/cases/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/case-manager'
    | '/claimant'
    | '/neutral'
    | '/registrar'
    | '/respondent'
    | '/unauthorized'
    | '/admin/cases'
    | '/admin/users'
    | '/auth/signin'
    | '/auth/signup'
    | '/cases/$id'
    | '/cases/new'
    | '/cases'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/case-manager'
    | '/claimant'
    | '/dashboard'
    | '/neutral'
    | '/registrar'
    | '/respondent'
    | '/unauthorized'
    | '/admin/cases'
    | '/admin/users'
    | '/auth/signin'
    | '/auth/signup'
    | '/cases/$id'
    | '/cases/new'
    | '/cases/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CaseManagerRoute: typeof CaseManagerRoute
  ClaimantRoute: typeof ClaimantRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  NeutralRoute: typeof NeutralRoute
  RegistrarRoute: typeof RegistrarRoute
  RespondentRoute: typeof RespondentRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CasesIdRoute: typeof CasesIdRoute
  CasesNewRoute: typeof CasesNewRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/respondent': {
      id: '/respondent'
      path: '/respondent'
      fullPath: '/respondent'
      preLoaderRoute: typeof RespondentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neutral': {
      id: '/neutral'
      path: '/neutral'
      fullPath: '/neutral'
      preLoaderRoute: typeof NeutralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claimant': {
      id: '/claimant'
      path: '/claimant'
      fullPath: '/claimant'
      preLoaderRoute: typeof ClaimantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-manager': {
      id: '/case-manager'
      path: '/case-manager'
      fullPath: '/case-manager'
      preLoaderRoute: typeof CaseManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/new': {
      id: '/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof CasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCasesRoute: typeof AdminCasesRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCasesRoute: AdminCasesRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CaseManagerRoute: CaseManagerRoute,
  ClaimantRoute: ClaimantRoute,
  DashboardRoute: DashboardRouteWithChildren,
  NeutralRoute: NeutralRoute,
  RegistrarRoute: RegistrarRoute,
  RespondentRoute: RespondentRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  CasesIdRoute: CasesIdRoute,
  CasesNewRoute: CasesNewRoute,
  CasesIndexRoute: CasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
